### ISSUE TITLE
Sample Content,WebAgency ,This add-on has not been activated successfully

### ISSUE THREAD

**Issue by mrafea** [Sitefinity-SDK/Telerik.Sitefinity.Samples.Quantum#15]
Regarding Sample Content ,the instructions:
(
import the sample content for the web agency add-on, log into the backend, navigate to Administration->Add-ons, click on the WebAgency add-on and activate it.
 )
when try to activation an error appear :

(This add-on has not been activated successfully. Please check the log for further information )

if i try again ,  a new error 

(

WebAgency
This add-on cannot be activated, because its files are missing or corrupted

)

how to fix this issue ?

**Comment by nader-dab** [comment]
Hello,

Unfortunately I was not able to reproduce the issue locally.

The *"files missing or corrupted"* error that you get indicates that the add-on files are no longer present in the **~\App_Data\Sitefinity\AddOns\WebAgency** folder of your website. 

If possible, could you please download the repository and activate the add-on once again. Please make sure to remove all log files from the **~\App_Data\Sitefinity\Logs** folder before activating the add-on. 

If the issue persists, please provide us with the **ContentImport.log**, **Error.log** and **PackagingTrace.log** files so we can analyse the cause for the error.

Thank you for your cooperation.

**Comment by mrafea** [comment]
i had tried with latest version and it worked successfully
Thanks Eng. Nader Dabour
