### ISSUE TITLE
Getting "No Pages Created Yet" message

### ISSUE THREAD

**Issue by DugzNugz** [Sitefinity-SDK/Telerik.Sitefinity.Samples.Quantum#20]
I just got this new 10.1.6500 version of the Quantum site up and running and I am getting the message "You see this screen because there are no pages created yet". I am able to login to the back end and can verify there are no pages. But I do see other stuff listed there like products and orders. Could it be that this version did not include the needed pages in order to run this demo site properly?

**Comment by nader-dab** [comment]
You can import sample pages and content by using the Add-ons module. To do so log into the backend, navigate to Administration->Add-ons, click on the WebAgency add-on and activate it. That should do the trick.

**Comment by DugzNugz** [comment]
That worked, thanks for the help.
